interface FeaturedPanel {
  image: string;
  imageAlt: string;
  eyebrow: string;
  title: string;
  description: string;
  cta: string;
  href: string;
}

export interface NavLinkV2 {
  label: string;
  href: string;
  description: string;
  featured: FeaturedPanel;
}

/** A hardware product family (used in 3-column Hardware mega menu) */
export interface HardwareFamily {
  label: string;
  href: string;
  tagline: string;
  featured: FeaturedPanel;
  products: NavLinkV2[];
}

export interface NavItemV2 {
  label: string;
  href: string;
  tagline: string;
  links: NavLinkV2[];
  sectionFeatured: FeaturedPanel;
  /** When provided, renders the 3-column hardware mega menu instead of the standard 2-column panel */
  families?: HardwareFamily[];
}

export const NAV_CONFIG_V2: NavItemV2[] = [
  {
    label: "Solutions",
    href: "/solutions",
    tagline: "Purpose-built modules for every warehouse challenge.",
    sectionFeatured: {
      image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Warehouse overview",
      eyebrow: "Not sure where to begin?",
      title: "Find Your Starting Point",
      description: "Answer a few questions and we'll map the right solution to your warehouse operation.",
      cta: "Start Assessment",
      href: "/get-started",
    },
    links: [
      {
        label: "Rack Intelligence",
        href: "/solutions/rack-intelligence",
        description: "Improve rack safety, compliance, and lifecycle management",
        featured: {
          image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Rack inspection in warehouse",
          eyebrow: "Powered by IRDS",
          title: "Rack Intelligence",
          description: "AI-driven rack monitoring that flags damage, overload risk, and compliance gaps before they become incidents.",
          cta: "Explore Rack Intelligence",
          href: "/solutions/rack-intelligence",
        },
      },
      {
        label: "MHE Intelligence",
        href: "/solutions/mhe-intelligence",
        description: "Improve vehicle safety and operator productivity",
        featured: {
          image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Forklift in warehouse",
          eyebrow: "Powered by MEPS + RTSS",
          title: "MHE Intelligence",
          description: "Real-time vehicle monitoring, operator behaviour analytics, and predictive utilisation across your entire MHE fleet.",
          cta: "Explore MHE Intelligence",
          href: "/solutions/mhe-intelligence",
        },
      },
      {
        label: "Inventory Intelligence",
        href: "/solutions/inventory-intelligence",
        description: "Real-time inventory visibility across every location",
        featured: {
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Analytics dashboard",
          eyebrow: "Live Inventory",
          title: "Inventory Intelligence",
          description: "Continuous stock visibility at every bin, bay, and pallet — zero blind spots, zero manual cycle counts.",
          cta: "Explore Inventory Intelligence",
          href: "/solutions/inventory-intelligence",
        },
      },
      {
        label: "Warehouse Execution",
        href: "/solutions/warehouse-execution",
        description: "Orchestrate warehouse operations with precision and speed",
        featured: {
          image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
          imageAlt: "AI camera technology",
          eyebrow: "Powered by ATOS",
          title: "Warehouse Execution",
          description: "Intelligent task orchestration that routes work to the right resource at the right time — automatically.",
          cta: "Explore Warehouse Execution",
          href: "/solutions/warehouse-execution",
        },
      },
      {
        label: "MHE Diagnostics",
        href: "/solutions/mhe-diagnostics",
        description: "Predictive maintenance before failures occur",
        featured: {
          image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Forklift maintenance",
          eyebrow: "Powered by IMDS",
          title: "MHE Diagnostics",
          description: "Vibration, thermal, and kinematic sensors flag faults weeks before breakdown — keeping your fleet available.",
          cta: "Explore MHE Diagnostics",
          href: "/solutions/mhe-diagnostics",
        },
      },
      {
        label: "Management Intelligence",
        href: "/solutions/management-intelligence",
        description: "Enterprise-wide dashboards and performance insight",
        featured: {
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Management dashboard",
          eyebrow: "Powered by AIMS",
          title: "Management Intelligence",
          description: "A unified command layer that surfaces KPIs, safety scores, and operational health across every site you run.",
          cta: "Explore Management Intelligence",
          href: "/solutions/management-intelligence",
        },
      },
    ],
  },

  {
    label: "Platform",
    href: "/platform",
    tagline: "One OS for your entire warehouse estate.",
    sectionFeatured: {
      image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Digital twin platform",
      eyebrow: "See it in action",
      title: "The RAMS Operating System",
      description: "One platform connecting hardware, AI, inspections, and execution across your entire warehouse estate.",
      cta: "Explore Platform",
      href: "/platform",
    },
    links: [
      {
        label: "Digital Twin",
        href: "/platform/digital-twin",
        description: "Live warehouse replica updated in real time",
        featured: {
          image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Digital twin visualisation",
          eyebrow: "Live Replica",
          title: "Digital Twin",
          description: "A centimetre-accurate, real-time digital replica of your warehouse — updated continuously from sensors, cameras, and RTLS.",
          cta: "Explore Digital Twin",
          href: "/platform/digital-twin",
        },
      },
      {
        label: "AI Operational Intelligence",
        href: "/platform/ai-intelligence",
        description: "Machine learning models trained on warehouse data",
        featured: {
          image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
          imageAlt: "AI intelligence system",
          eyebrow: "Machine Learning",
          title: "AI Operational Intelligence",
          description: "Warehouse-native ML models that detect anomalies, predict failures, and surface recommendations — in real time.",
          cta: "Explore AI Intelligence",
          href: "/platform/ai-intelligence",
        },
      },
      {
        label: "Execution Engine",
        href: "/platform/execution-engine",
        description: "Decision-to-action in milliseconds, at scale",
        featured: {
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Execution engine dashboard",
          eyebrow: "Sub-50ms Response",
          title: "Execution Engine",
          description: "From decision to directed action in under 50ms — routing tasks, triggering alerts, and orchestrating workflows at scale.",
          cta: "Explore Execution Engine",
          href: "/platform/execution-engine",
        },
      },
      {
        label: "Integrations",
        href: "/platform/integrations",
        description: "Connect WMS, ERP, MHE, and IoT systems seamlessly",
        featured: {
          image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
          imageAlt: "System integrations",
          eyebrow: "Open Integration Layer",
          title: "Integrations",
          description: "Pre-built connectors for SAP, Oracle, Manhattan, Blue Yonder, and 60+ WMS, ERP, and MHE systems.",
          cta: "View Integrations",
          href: "/platform/integrations",
        },
      },
      {
        label: "Security",
        href: "/platform/security",
        description: "Enterprise-grade data security and compliance",
        featured: {
          image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Security and compliance",
          eyebrow: "Enterprise Security",
          title: "Security",
          description: "ISO 27001, SOC 2 Type II, and GDPR-compliant architecture — with end-to-end encryption and role-based access control.",
          cta: "View Security",
          href: "/platform/security",
        },
      },
    ],
  },

  {
    label: "Hardware",
    href: "/hardware",
    tagline: "Every sensor, camera, and compute unit — built for the warehouse floor.",
    links: [],
    sectionFeatured: {
      image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
      imageAlt: "RAMS hardware ecosystem",
      eyebrow: "One connected edge platform",
      title: "Hardware Ecosystem",
      description: "Every RAMS device — from edge compute to AI cameras to autonomous inspection — works as a unified system.",
      cta: "Explore Hardware",
      href: "/hardware",
    },
    families: [
      {
        label: "AI Vision Systems",
        href: "/hardware/ai-vision",
        tagline: "360° perception across every warehouse zone",
        featured: {
          image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
          imageAlt: "AI vision cameras in warehouse",
          eyebrow: "AI Vision Systems",
          title: "Prevent accidents before they happen.",
          description: "Multi-spectral AI cameras and in-cab monitoring deliver continuous, real-time awareness across every aisle, zone, and vehicle — no blind spots.",
          cta: "Explore AI Vision",
          href: "/hardware/ai-vision",
        },
        products: [
          {
            label: "AI Cameras",
            href: "/hardware/ai-cameras",
            description: "360° warehouse perception at scale",
            featured: {
              image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
              imageAlt: "AI cameras mounted in warehouse",
              eyebrow: "AI Vision Systems",
              title: "AI Cameras",
              description: "Multi-spectral cameras with on-device inference — detecting objects, people, and hazards across every zone in real time.",
              cta: "Explore AI Cameras",
              href: "/hardware/ai-cameras",
            },
          },
          {
            label: "Driver Monitoring",
            href: "/hardware/driver-monitoring",
            description: "In-cab operator safety and behaviour",
            featured: {
              image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80&auto=format&fit=crop",
              imageAlt: "In-cab driver monitoring",
              eyebrow: "AI Vision Systems",
              title: "Driver Monitoring",
              description: "AI detects fatigue, distraction, and unsafe behaviour in real time — issuing instant alerts and logging every event for managers.",
              cta: "Explore Driver Monitoring",
              href: "/hardware/driver-monitoring",
            },
          },
          {
            label: "PPE Detection",
            href: "/hardware/ppe-detection",
            description: "Automated compliance monitoring",
            featured: {
              image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
              imageAlt: "PPE compliance monitoring",
              eyebrow: "AI Vision Systems",
              title: "PPE Detection",
              description: "Continuous AI monitoring flags PPE violations the moment they occur — alerting supervisors before a near-miss becomes an incident.",
              cta: "Explore PPE Detection",
              href: "/hardware/ppe-detection",
            },
          },
        ],
      },
      {
        label: "OmniBox Platform",
        href: "/hardware/omnibox",
        tagline: "Warehouse-grade edge compute for every environment",
        featured: {
          image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
          imageAlt: "OmniBox edge compute platform",
          eyebrow: "OmniBox Platform",
          title: "Local intelligence. Zero cloud dependency.",
          description: "The OmniBox family runs the full RAMS inference stack at the edge — sub-10ms response, continuous uptime, built for the harshest warehouse environments.",
          cta: "Explore OmniBox",
          href: "/hardware/omnibox",
        },
        products: [
          {
            label: "OmniBox Edge",
            href: "/hardware/omnibox-edge",
            description: "Local AI inference at the rack",
            featured: {
              image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
              imageAlt: "OmniBox Edge unit",
              eyebrow: "OmniBox Platform",
              title: "OmniBox Edge",
              description: "Rack-mounted compute that runs RAMS models locally — zero cloud dependency, sub-10ms response, IP65 rated.",
              cta: "Explore OmniBox Edge",
              href: "/hardware/omnibox-edge",
            },
          },
          {
            label: "OmniBox AI",
            href: "/hardware/omnibox-ai",
            description: "High-performance neural compute",
            featured: {
              image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
              imageAlt: "OmniBox AI compute",
              eyebrow: "OmniBox Platform",
              title: "OmniBox AI",
              description: "High-density GPU compute that runs multiple RAMS inference models in parallel — purpose-built for enterprise warehouse deployments.",
              cta: "Explore OmniBox AI",
              href: "/hardware/omnibox-ai",
            },
          },
          {
            label: "OmniBox Motion",
            href: "/hardware/omnibox-motion",
            description: "Kinematic sensing and 6-axis IMU",
            featured: {
              image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80&auto=format&fit=crop",
              imageAlt: "OmniBox Motion sensor on MHE",
              eyebrow: "OmniBox Platform",
              title: "OmniBox Motion",
              description: "6-axis IMU and kinematic sensors mounted to MHE — capturing vibration, tilt, and impact data for predictive diagnostics.",
              cta: "Explore OmniBox Motion",
              href: "/hardware/omnibox-motion",
            },
          },
          {
            label: "OmniBox Core",
            href: "/hardware/omnibox-core",
            description: "Central orchestration unit",
            featured: {
              image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
              imageAlt: "OmniBox Core orchestration",
              eyebrow: "OmniBox Platform",
              title: "OmniBox Core",
              description: "The central hub that ties every RAMS edge device together — unified communication, power management, and orchestration in one unit.",
              cta: "Explore OmniBox Core",
              href: "/hardware/omnibox-core",
            },
          },
        ],
      },
      {
        label: "Location Intelligence",
        href: "/hardware/location",
        tagline: "Centimetre-accurate spatial awareness across every square metre",
        featured: {
          image: "https://images.unsplash.com/photo-1569605803663-e9337d9f7546?w=800&q=80&auto=format&fit=crop",
          imageAlt: "LiDAR warehouse spatial mapping",
          eyebrow: "Location Intelligence",
          title: "Know where everything is. Always.",
          description: "LiDAR, RTLS, and indoor positioning work together to give you a live, centimetre-accurate map of every asset, vehicle, and person in your facility.",
          cta: "Explore Location",
          href: "/hardware/location",
        },
        products: [
          {
            label: "LiDAR",
            href: "/hardware/lidar",
            description: "3D spatial mapping at centimetre accuracy",
            featured: {
              image: "https://images.unsplash.com/photo-1569605803663-e9337d9f7546?w=800&q=80&auto=format&fit=crop",
              imageAlt: "LiDAR spatial mapping",
              eyebrow: "Location Intelligence",
              title: "LiDAR",
              description: "Industrial LiDAR builds a continuously updated 3D map of your warehouse — detecting layout changes, obstructions, and hazards automatically.",
              cta: "Explore LiDAR",
              href: "/hardware/lidar",
            },
          },
          {
            label: "RTLS",
            href: "/hardware/rtls",
            description: "Real-time location for every asset",
            featured: {
              image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
              imageAlt: "RTLS asset tracking",
              eyebrow: "Location Intelligence",
              title: "RTLS",
              description: "Sub-metre real-time tracking for forklifts, pallets, people, and fixed assets — across every square metre of your facility.",
              cta: "Explore RTLS",
              href: "/hardware/rtls",
            },
          },
          {
            label: "Indoor Positioning",
            href: "/hardware/indoor-positioning",
            description: "UWB precision in complex environments",
            featured: {
              image: "https://images.unsplash.com/photo-1569605803663-e9337d9f7546?w=800&q=80&auto=format&fit=crop",
              imageAlt: "Indoor positioning system",
              eyebrow: "Location Intelligence",
              title: "Indoor Positioning",
              description: "UWB-based positioning with sub-metre accuracy across multi-level, high-rack warehouse environments where GPS cannot reach.",
              cta: "Explore Indoor Positioning",
              href: "/hardware/indoor-positioning",
            },
          },
        ],
      },
      {
        label: "Guided Inspection Systems",
        href: "/hardware/inspection",
        tagline: "Autonomous inspection that never misses a thing",
        featured: {
          image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
          imageAlt: "AirScan drone rack inspection",
          eyebrow: "Guided Inspection Systems",
          title: "Inspect everything. Miss nothing.",
          description: "AirScan drones and FloorScan robots run scheduled inspections autonomously — capturing rack defects, floor hazards, and compliance issues before they escalate.",
          cta: "Explore Inspection",
          href: "/hardware/inspection",
        },
        products: [
          {
            label: "AirScan",
            href: "/hardware/airscan",
            description: "Autonomous drone rack inspection",
            featured: {
              image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
              imageAlt: "AirScan drone in warehouse aisle",
              eyebrow: "Guided Inspection Systems",
              title: "AirScan",
              description: "Autonomous drones fly rack aisles on schedule, capturing every beam, upright, and connector for AI-powered defect analysis.",
              cta: "Explore AirScan",
              href: "/hardware/airscan",
            },
          },
          {
            label: "FloorScan",
            href: "/hardware/floorscan",
            description: "Ground-level autonomous inspection robot",
            featured: {
              image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
              imageAlt: "FloorScan robot inspection",
              eyebrow: "Guided Inspection Systems",
              title: "FloorScan",
              description: "Ground-level scanning robot inspects floor-level rack components, floor markings, and clearances — on a scheduled, unmanned basis.",
              cta: "Explore FloorScan",
              href: "/hardware/floorscan",
            },
          },
          {
            label: "Sensor Stack",
            href: "/hardware/sensor-stack",
            description: "Integrated multi-sensor architecture",
            featured: {
              image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
              imageAlt: "Sensor Stack unit",
              eyebrow: "Guided Inspection Systems",
              title: "Sensor Stack",
              description: "A pre-integrated rack-mounted bundle combining vibration, load, temperature, and visual sensing — one unit, zero integration effort.",
              cta: "Explore Sensor Stack",
              href: "/hardware/sensor-stack",
            },
          },
        ],
      },
    ],
  },

  {
    label: "Services",
    href: "/services",
    tagline: "Expert delivery from certified warehouse engineers.",
    sectionFeatured: {
      image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Engineer performing warehouse inspection",
      eyebrow: "Need an inspection?",
      title: "Book an Inspection",
      description: "Request a certified rack inspection or MHE assessment — on-site or remote, with a 48-hour response.",
      cta: "Request Quote",
      href: "/services/request-quote",
    },
    links: [
      {
        label: "Rack Inspection",
        href: "/services/rack-inspection",
        description: "Certified rack safety assessments on-site or remote",
        featured: {
          image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Rack inspection service",
          eyebrow: "SEMA Certified",
          title: "Rack Inspection",
          description: "SEMA and FEM-accredited engineers assess every upright, beam, and connector — with a full digital report in 24 hours.",
          cta: "Book Rack Inspection",
          href: "/services/rack-inspection",
        },
      },
      {
        label: "Structural Verification",
        href: "/services/structural-verification",
        description: "Load capacity analysis and compliance reporting",
        featured: {
          image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Structural verification",
          eyebrow: "Load Analysis",
          title: "Structural Verification",
          description: "Certified structural engineers validate rack load capacity and issue compliance certificates for insurance and regulatory bodies.",
          cta: "Learn More",
          href: "/services/structural-verification",
        },
      },
      {
        label: "Inventory Audit",
        href: "/services/inventory-audit",
        description: "Full-warehouse inventory accuracy verification",
        featured: {
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Inventory audit",
          eyebrow: "Accuracy Audit",
          title: "Inventory Audit",
          description: "AI-assisted full-warehouse cycle counts that deliver 99.8%+ accuracy — in a fraction of the time of manual audit.",
          cta: "Request Audit",
          href: "/services/inventory-audit",
        },
      },
      {
        label: "MHE Productivity Assessment",
        href: "/services/mhe-productivity",
        description: "Identify vehicle utilisation and efficiency gaps",
        featured: {
          image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80&auto=format&fit=crop",
          imageAlt: "MHE productivity assessment",
          eyebrow: "Fleet Review",
          title: "MHE Productivity Assessment",
          description: "Data-driven fleet utilisation analysis that pinpoints idle time, route inefficiency, and right-sizing opportunities.",
          cta: "Book Assessment",
          href: "/services/mhe-productivity",
        },
      },
      {
        label: "Operational Assessment",
        href: "/services/operational-assessment",
        description: "End-to-end warehouse operational review",
        featured: {
          image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Operational assessment",
          eyebrow: "Full Review",
          title: "Operational Assessment",
          description: "A structured 5-day on-site review covering throughput, accuracy, safety, and cost — with a prioritised improvement roadmap.",
          cta: "Request Assessment",
          href: "/services/operational-assessment",
        },
      },
      {
        label: "Deployment & Support",
        href: "/services/deployment-support",
        description: "Implementation, training, and managed support",
        featured: {
          image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Deployment and support",
          eyebrow: "Managed Delivery",
          title: "Deployment & Support",
          description: "RAMS engineers handle every step — hardware install, software configuration, operator training, and 24/7 managed support.",
          cta: "Talk to Us",
          href: "/services/deployment-support",
        },
      },
    ],
  },

  {
    label: "Industries",
    href: "/industries",
    tagline: "Deep sector expertise, purpose-built configurations.",
    sectionFeatured: {
      image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Industry warehouse solutions",
      eyebrow: "Purpose-built for every sector",
      title: "Explore Industry Solutions",
      description: "See how RAMS adapts to the compliance, safety, and operational demands of your industry.",
      cta: "View Industries",
      href: "/industries",
    },
    links: [
      {
        label: "Manufacturing",
        href: "/industries/manufacturing",
        description: "End-to-end production floor visibility",
        featured: {
          image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Manufacturing warehouse",
          eyebrow: "Manufacturing",
          title: "Production Floor Intelligence",
          description: "Real-time visibility from raw material intake to finished goods dispatch — with AI-driven quality and compliance checks throughout.",
          cta: "Explore Manufacturing",
          href: "/industries/manufacturing",
        },
      },
      {
        label: "Warehousing & Distribution",
        href: "/industries/warehousing",
        description: "Optimise throughput and accuracy",
        featured: {
          image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Warehousing and distribution",
          eyebrow: "Warehousing & Distribution",
          title: "Throughput at Scale",
          description: "Maximise pick rates, reduce errors, and keep every SLA green — across single sites and multi-node distribution networks.",
          cta: "Explore Warehousing",
          href: "/industries/warehousing",
        },
      },
      {
        label: "Food & Beverage",
        href: "/industries/food-beverage",
        description: "Cold chain and FIFO compliance",
        featured: {
          image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Cold storage warehouse",
          eyebrow: "Food & Beverage",
          title: "Cold Chain Intelligence",
          description: "Continuous temperature monitoring, automated FIFO enforcement, and real-time shelf-life tracking across chilled and frozen environments.",
          cta: "Explore Food & Beverage",
          href: "/industries/food-beverage",
        },
      },
      {
        label: "Pharmaceutical",
        href: "/industries/pharmaceutical",
        description: "Regulated storage and traceability",
        featured: {
          image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Pharmaceutical warehouse",
          eyebrow: "Pharmaceutical",
          title: "Regulated Traceability",
          description: "GMP-compliant storage monitoring, full chain-of-custody tracking, and automated serialisation for pharma and life sciences.",
          cta: "Explore Pharmaceutical",
          href: "/industries/pharmaceutical",
        },
      },
      {
        label: "E-Commerce",
        href: "/industries/ecommerce",
        description: "High-velocity order operations",
        featured: {
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
          imageAlt: "E-commerce fulfilment",
          eyebrow: "E-Commerce",
          title: "High-Velocity Fulfilment",
          description: "AI-optimised pick paths, dynamic slotting, and real-time order orchestration built for same-day and next-day delivery at scale.",
          cta: "Explore E-Commerce",
          href: "/industries/ecommerce",
        },
      },
      {
        label: "Logistics & 3PL",
        href: "/industries/logistics-3pl",
        description: "Multi-client warehouse management",
        featured: {
          image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Logistics and 3PL",
          eyebrow: "Logistics & 3PL",
          title: "Multi-Client Operations",
          description: "Segregated client views, flexible billing, and unified command across every contract — built for the complexity of 3PL at scale.",
          cta: "Explore Logistics & 3PL",
          href: "/industries/logistics-3pl",
        },
      },
      {
        label: "Retail",
        href: "/industries/retail",
        description: "Omnichannel fulfilment intelligence",
        featured: {
          image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Retail fulfilment",
          eyebrow: "Retail",
          title: "Omnichannel Fulfilment",
          description: "Unified inventory visibility across stores, DCs, and dark stores — enabling accurate, profitable omnichannel fulfilment.",
          cta: "Explore Retail",
          href: "/industries/retail",
        },
      },
      {
        label: "Automotive",
        href: "/industries/automotive",
        description: "Parts tracking and JIT compliance",
        featured: {
          image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Automotive parts warehouse",
          eyebrow: "Automotive",
          title: "JIT Parts Intelligence",
          description: "Precise parts tracking and sequencing that keeps production lines running — with zero tolerance for mis-picks or late delivery.",
          cta: "Explore Automotive",
          href: "/industries/automotive",
        },
      },
    ],
  },

  {
    label: "Resources",
    href: "/resources",
    tagline: "Research, guides, and expertise from the RAMS team.",
    sectionFeatured: {
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Warehouse AI Report 2026",
      eyebrow: "Latest insight",
      title: "Warehouse AI Report 2026",
      description: "How AI is reshaping safety, productivity, and compliance in enterprise warehouses globally.",
      cta: "Read Report",
      href: "/resources/warehouse-ai-report-2026",
    },
    links: [
      {
        label: "Case Studies",
        href: "/resources/case-studies",
        description: "Real-world customer outcomes",
        featured: {
          image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Customer case study",
          eyebrow: "Customer Stories",
          title: "Case Studies",
          description: "See how leading warehouse operators use RAMS to reduce incidents, cut costs, and accelerate throughput.",
          cta: "View Case Studies",
          href: "/resources/case-studies",
        },
      },
      {
        label: "Insights",
        href: "/resources/insights",
        description: "Expert warehouse intelligence articles",
        featured: {
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Insights articles",
          eyebrow: "Expert Analysis",
          title: "Insights",
          description: "Deep-dive articles on warehouse safety, AI, automation, and operational excellence from the RAMS engineering and advisory team.",
          cta: "Browse Insights",
          href: "/resources/insights",
        },
      },
      {
        label: "White Papers",
        href: "/resources/white-papers",
        description: "In-depth research and analysis",
        featured: {
          image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
          imageAlt: "White papers",
          eyebrow: "Research",
          title: "White Papers",
          description: "Original research on warehouse AI, rack safety standards, MHE fleet economics, and supply chain resilience.",
          cta: "Download White Papers",
          href: "/resources/white-papers",
        },
      },
      {
        label: "Videos",
        href: "/resources/videos",
        description: "Product demos and walkthroughs",
        featured: {
          image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Product video demos",
          eyebrow: "Watch & Learn",
          title: "Videos",
          description: "Platform walkthroughs, customer testimonials, and technical deep-dives — on demand.",
          cta: "Watch Videos",
          href: "/resources/videos",
        },
      },
      {
        label: "Technical Notes",
        href: "/resources/technical-notes",
        description: "Integration and API documentation",
        featured: {
          image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Technical documentation",
          eyebrow: "Developer Docs",
          title: "Technical Notes",
          description: "API references, integration guides, SDK documentation, and architecture notes for technical teams.",
          cta: "View Technical Notes",
          href: "/resources/technical-notes",
        },
      },
      {
        label: "Compliance Guides",
        href: "/resources/compliance",
        description: "SEMA, FEM, OSHA reference guides",
        featured: {
          image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Compliance guides",
          eyebrow: "Compliance",
          title: "Compliance Guides",
          description: "Practical reference guides for SEMA, FEM, OSHA, and EN 15635 rack safety standards — updated for 2026.",
          cta: "View Compliance Guides",
          href: "/resources/compliance",
        },
      },
      {
        label: "Downloads",
        href: "/resources/downloads",
        description: "Datasheets, brochures, and specs",
        featured: {
          image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Downloads library",
          eyebrow: "Asset Library",
          title: "Downloads",
          description: "Hardware datasheets, solution brochures, integration specs, and compliance certificates — all in one place.",
          cta: "Browse Downloads",
          href: "/resources/downloads",
        },
      },
      {
        label: "FAQ",
        href: "/resources/faq",
        description: "Answers to common questions",
        featured: {
          image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
          imageAlt: "FAQ",
          eyebrow: "Help Centre",
          title: "FAQ",
          description: "Answers to the most common questions about RAMS platform capabilities, deployment, pricing, and support.",
          cta: "View FAQ",
          href: "/resources/faq",
        },
      },
    ],
  },

  {
    label: "Company",
    href: "/company",
    tagline: "The team and mission behind warehouse operational intelligence.",
    sectionFeatured: {
      image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
      imageAlt: "RAMS team",
      eyebrow: "Our vision",
      title: "Why RAMS",
      description: "Operational intelligence should be reliable, deeply integrated, and built for the realities of enterprise warehousing.",
      cta: "About RAMS",
      href: "/company/about",
    },
    links: [
      {
        label: "About RAMS",
        href: "/company/about",
        description: "Our mission and story",
        featured: {
          image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
          imageAlt: "About RAMS",
          eyebrow: "Our Mission",
          title: "About RAMS",
          description: "We believe warehouse intelligence should be real, reliable, and deeply integrated — not a dashboard on top of broken data.",
          cta: "Our Story",
          href: "/company/about",
        },
      },
      {
        label: "Leadership",
        href: "/company/leadership",
        description: "Meet the executive team",
        featured: {
          image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Leadership team",
          eyebrow: "Executive Team",
          title: "Leadership",
          description: "Industry veterans from operations, engineering, and AI — united by a shared belief in the power of warehouse intelligence.",
          cta: "Meet the Team",
          href: "/company/leadership",
        },
      },
      {
        label: "Customers",
        href: "/company/customers",
        description: "Who trusts RAMS globally",
        featured: {
          image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
          imageAlt: "RAMS customers",
          eyebrow: "Global Customers",
          title: "Customers",
          description: "Trusted by enterprise warehouse operators across manufacturing, retail, pharma, and logistics — in 14 countries.",
          cta: "View Customers",
          href: "/company/customers",
        },
      },
      {
        label: "Partners",
        href: "/company/partners",
        description: "Technology and channel partners",
        featured: {
          image: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?w=800&q=80&auto=format&fit=crop",
          imageAlt: "RAMS partners",
          eyebrow: "Partner Ecosystem",
          title: "Partners",
          description: "A global network of technology, integration, and channel partners that extend RAMS capabilities across every region.",
          cta: "View Partners",
          href: "/company/partners",
        },
      },
      {
        label: "Careers",
        href: "/company/careers",
        description: "Join the RAMS team",
        featured: {
          image: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Careers at RAMS",
          eyebrow: "Join Us",
          title: "Careers",
          description: "We're building the future of warehouse intelligence. Join a team of engineers, scientists, and operators doing work that matters.",
          cta: "View Open Roles",
          href: "/company/careers",
        },
      },
      {
        label: "Certifications",
        href: "/company/certifications",
        description: "Standards and accreditations",
        featured: {
          image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Certifications",
          eyebrow: "Accreditations",
          title: "Certifications",
          description: "ISO 9001, ISO 27001, SEMA membership, and FEM accreditation — the standards that back every RAMS inspection and deployment.",
          cta: "View Certifications",
          href: "/company/certifications",
        },
      },
      {
        label: "Contact",
        href: "/contact",
        description: "Get in touch with our team",
        featured: {
          image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80&auto=format&fit=crop",
          imageAlt: "Contact RAMS",
          eyebrow: "Get in Touch",
          title: "Contact",
          description: "Speak to a RAMS specialist about your warehouse challenges. We respond within one business day.",
          cta: "Contact Us",
          href: "/contact",
        },
      },
    ],
  },
];
